framework:
  rate_limiter:
#    auth:
#      # use 'sliding_window' if you prefer that policy
#      policy: 'fixed_window'
#      limit: 5
#      interval: '60 minutes'
    regular_api:
      policy: 'sliding_window'
      limit: 10
      interval: '1 second'